name: magic-mirror
services:
  server:
    ports:
      - 4221:3000
    image: ghcr.io/thepurplebubble/magic-mirror:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SLACK_LOG_CHANNEL=C07ALMZQK8T
      - PB_SLACK_BOT_TOKEN=xoxb-
      - PB_SLACK_USER_TOKEN=xoxp-
      - PB_SLACK_APP_TOKEN=xapp-
      - PB_SLACK_SIGNING_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - PB_SLACK_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - PB_SLACK_CLIENT_ID=xxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx
      - PB_SLACK_APP_ID=A07B9LJ80D6
      - HC_SLACK_BOT_TOKEN=xoxb-
      - HC_SLACK_USER_TOKEN=xoxp-
      - HC_SLACK_APP_TOKEN=xapp-1-
      - HC_SLACK_SIGNING_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - HC_SLACK_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - HC_SLACK_CLIENT_ID=xxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx
      - HC_SLACK_APP_ID=A07AK8PC5FG
      - ADMINS=U0xxxxxxxxx # comma separated list of slack user IDs
    init: true
